version: "3"

services:
  node:
    build: .
    depends_on:
      - mongo
    image: acgomes68/alpine-node:latest
    container_name: node-${APP_NAME}
    command: yarn start
    ports:
    - ${APP_PORT}:3333
    volumes:
    - .:/home/node/app

  mongo:
    image: mvertes/alpine-mongo:latest
    container_name: mongo-${APP_NAME}
    ports:
    - ${MONGO_PORT}:27017
    volumes:
    - modelo-data:/data/db

volumes:
    modelo-data:
